### ISSUE TITLE
Proposal: add metrics KeysNumber

### ISSUE THREAD

**Issue by choleraehyq** [dgraph-io/ristretto#135]
Here I want to  get the key numbers current cache contains. Seems it's easy to maintain.

**Comment by martinmr** [comment]
Just to make sure we are on the same page you want Ristretto to report the current number of key-value pairs stored in the cache.

This would be easy to code but it's not as straight-forward as the other metrics because Ristretto uses a sharded map so we'd need to iterate through the maps (while holding the locks for each shard) so there are performance implications. All the other metrics are reported via atomic counters which means there's no locking involved.

I'll bring it up to @manishrjain to see what he thinks.

**Comment by blasrodri** [comment]
@martinmr would it be possible to store an atomic integer that reflects this number, and gets updated every time a key is added/evicted?

**Comment by minhaj-shakeel** [comment]
**GitHub Issues is being deprecated.**
 This issue has been moved to [link](https://discuss.dgraph.io/t/0). You can follow the conversation there and also subscribe to updates by changing your notification preferences. 

 <img src="https://github.com/dgraph-io/github-utils/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/7894). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/github-utils/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8416). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/github-utils/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8421). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
