### ISSUE TITLE
Feature Request: Transactions

### ISSUE THREAD

**Issue by MarcErdmann** [dgraph-io/ristretto#152]
It would be great if Ristretto can somehow provide transactions.

**Comment by jarifibrahim** [comment]
Related to https://github.com/dgraph-io/ristretto/issues/151

**Comment by martinmr** [comment]
Thanks for your feature request. Unfortunately, transactions are probably beyond the scope of this project at the moment and I don't think the current design would lend itself to a feature like this given that the majority of the design decisions were biased towards reducing contention and speed. Having to keep track of transactions would most likely require a different approach.

I'll keep the issue open so that the community can comment.

**Comment by minhaj-shakeel** [comment]
**GitHub Issues is being deprecated.**
 This issue has been moved to [link](https://discuss.dgraph.io/t/0). You can follow the conversation there and also subscribe to updates by changing your notification preferences. 

 <img src="https://github.com/dgraph-io/github-utils/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8422). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
