### ISSUE TITLE
[Documentation]: Describe guarantees (or lack thereof) under aliased mutation of arguments and return values

### ISSUE THREAD

**Issue by varungandhi-src** [dgraph-io/ristretto#381]
### What version of Ristretto is the target?

Latest

### Documentation.

The docs for the `Cache` type don't say anything about the interaction of aliased mutations with Get/Set. Is it fair to assume the following: "It is NOT safe to modify the return value of Get or to modify the key or value that were passed to Set."

Or does the implementation do deep-copying?

**Comment by mangalaman93** [comment]
This is a valid point, we will work on updating the doc. Though, what you pass to the `Set` function or equivalent, that is what gets stored in the cache. For example, if you pass a `uint64` type, it would be stored as is and if you modify the variable, the value in the cache would not get updated because `uint64` will be passed as a value. Whereas, if you provide a `[]byte`, the underlined array is shared. If you update the underlined array, the value in the cache gets updated as well. I am gonna keep the issue open until we update the docs. Thanks for raising the issue.
