### ISSUE TITLE
[QUESTION]: When will there be a new release (v2 to maintain compatibility with libraries using the old version)?

### ISSUE THREAD

**Issue by flymedllva** [dgraph-io/ristretto#386]
### Question.

The library has not received a new release (tag) for a long time, although many bugs have been fixed, generics have been added (breaking compatibility of packages using ristretto).
When will there be a release?

**Comment by flymedllva** [comment]
Generics appearing in ristretto break compatibility of packages not updated to the new version of ristretto
Since ristretto can be used in libraries it is important...
The new tag doesn't seem to save this situation and we should do github.com/dgraph-io/ristretto/v2 to avoid breaking compatibility with libraries using the old version without generics.

**Comment by verkaufer** [comment]
@ryanfoxtyler Also interested in getting an officially tagged release for this library and then getting https://github.com/dgraph-io/badger updated with the tagged dependency. 

I was running into conflicts using BadgerDB [alongside ory/fosite](https://github.com/ory/fosite/issues/825) because it doesn't (yet) use the proper generic instantiation syntax. I couldn't downgrade ristretto to an earlier version either because BadgerDB needed something greater than 0.11.0 :)

**Comment by jchappelow** [comment]
> The new tag doesn't seem to save this situation and we should do github.com/dgraph-io/ristretto/v2 to avoid breaking compatibility with libraries using the old version without generics.

Completely agree.  I just saw this issue after reporting our trouble with badger and generics in https://github.com/dgraph-io/ristretto/issues/394#issuecomment-2389802911

**Comment by mangalaman93** [comment]
We just pushed released for badger https://github.com/dgraph-io/badger/releases/tag/v4.3.1 and ristretto https://github.com/dgraph-io/ristretto/releases/tag/v1.0.0. Badger v4.3.1 uses the latest v1.0.0 ristretto. I am going to close this issue but feel free to reopen if needed. Thanks
